// ========================================== //
// This file is generated by readSamplePid.py //
// ========================================== //


#ifndef __SAMPLE_H__
#define __SAMPLE_H__



// ===  =============== === //
// ===  FISSION CHAMBER === //
// ===  =============== === //

#define FC 1  // if 0: no FC defined in the DAQ

static int LabelFC[11] = {0,0,0,0,0,3,0,0,0,0,0};



// ===  ======================== === //
// ===  CHI-NU NEUTRON DETECTORS === //
// ===  ======================== === //

#define CHINU 0  // if 0: no Chi-Nu detector defined in the DAQ



// ===  ==================== === //
// ===  B3 NEUTRON DETECTORS === //
// ===  ==================== === //

#define B3 1  // if 0: no B3 detector defined in the DAQ

static int Label_B3_LG[4] = {1,0,0,0};

static int Label_B3_HG[4] = {2,0,0,0};



// ===  ====== === //
// ===  PULSER === //
// ===  ====== === //

#define PULSER 0  // if 0: no pulser defined in the DAQ



// ===  == === //
// ===  HF === //
// ===  == === //

#define HF 0  // if 0: no HF defined in the DAQ



// ===  =========== === //
// ===  MACRO PULSE === //
// ===  =========== === //

#define MACRO 0  // if 0: no Macro Pulse defined in the DAQ



// ===  =========================== === //
// ===  FOR GENERAL MAPPING PURPOSE === //
// ===  =========================== === //

static int Label2Ch[4] = {1,1,6,0};

static int DetType[4] = {3,3,1,0};

static int DetSubType[4] = {21,22,0,0};



#endif //__SAMPLE_H___