{
  gStyle->SetPalette(1);
  gStyle->SetLabelSize(0.04,"xyz");
  gSystem->Load("../ClassDef/RawCoincData_C.so");
  gSystem->Load("../ClassDef/RawSourceData_C.so");
  gSystem->Load("../ClassDef/FC_RawMultHistos_C.so");
  gSystem->Load("../ClassDef/FC_RawQHistos_C.so");
  gSystem->Load("../ClassDef/FC_RawToFHistos_C.so");
  gSystem->Load("../ClassDef/CHINU_RawMultHistos_C.so");
  gSystem->Load("../ClassDef/CHINU_RawQHistos_C.so");
  gSystem->Load("../ClassDef/CHINU_RawToFHistos_C.so");
  gSystem->Load("../ClassDef/CHINU_RawBkgToFHistos_C.so");
  gSystem->Load("../ClassDef/B3_RawMultHistos_C.so");
  gSystem->Load("../ClassDef/B3_RawQHistos_C.so");
  gSystem->Load("../ClassDef/B3_RawToFHistos_C.so");
  gSystem->Load("../ClassDef/HF_RawMultHistos_C.so");
  gSystem->Load("../ClassDef/HF_RawQHisto_C.so");
  gSystem->Load("../ClassDef/PULSER_RawMultHistos_C.so");
  gSystem->Load("../ClassDef/PULSER_RawQHisto_C.so");
}
